name: incuriousfilms.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82666
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#b3aeaf'
    - '#32351d'
    - '#835864'
    - '#f46d77'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
