name: incuriousfilms.com
favicon: null
layout_spectrum: 0.36061802972108126
typography_spectrum: 0.4881578723434359
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9544193660840392
  lightness: 0.010424212785437703
  saturation: 0.7028077132999897
  rhythmicContrast: 0.3507347460836172
purpose: []
