name: incuriousfilms.com
favicon: null
layout_spectrum: 0.24867
typography_spectrum: 0.82666
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaeaea'
    - '#01c9ea'
    - '#415c83'
    - '#767c8b'
    - '#b2b4b1'
  brandStrength: 0
  lightness: 0.0625
  saturation: 0.0625
  rhythmicContrast: 0.25
purpose: []
